"""empty message

Revision ID: 522058644f6a
Revises: 
Create Date: 2024-03-24 22:41:36.320737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522058644f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_item')
    # ### end Alembic commands ###
